spring:
  datasource:
    url: jdbc:mysql://localhost:3306/assignment1?allowPublicKeyRetrieval=true&useSSL=false
    username: sha256user
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
